# Generated by Django 3.1 on 2020-08-16 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_post', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_myself', models.TextField()),
                ('date_of_birth', models.DateTimeField()),
                ('hometown', models.CharField(max_length=254)),
                ('present_location', models.CharField(max_length=254)),
                ('geo_location', models.CharField(max_length=254)),
                ('facebook', models.URLField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True, max_length=254)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('interests', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=254)),
                ('username', models.CharField(blank=True, max_length=254)),
                ('user_role', models.CharField(choices=[(0, 'Admin'), (1, 'Moderator'), (2, 'Member')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_last_reply', models.DateTimeField()),
                ('name_of_last_poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.users')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='name_of_publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.users'),
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('number_of_threads', models.IntegerField()),
                ('number_of_posts', models.IntegerField()),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.thread')),
            ],
        ),
    ]
